const Experiences = [
  {
    position: "Freelance Developer",
    company: "Self Employed",
    companyHref: "https://www.linkedin.com/in/samuel-ou-0510s/",
    date: "Feb 2024 - Present ",
    src: "/logo.png",
    backgroundColor: "#ffffff",
    fontColor: "#005B6F",
    description: [
      "Collaborated directly with founder and design team of private startup to build and improve key features",
      "Led full development lifecycle, building an automated system for customer orders and inventory workflows",
      "Created custom management system specific to founder needs, decreasing manual input and tracking by over 40%",
      "Currently developing an ecommerce platform with AWS, PostgreSQL, TypeScript, React",
    ],
  },
  {
    position: "Software Engineering Fellow",
    company: "Headstarter AI",
    companyHref: "https://www.linkedin.com/company/headstarterai/mycompany/",
    date: "Jul 2024 - Sep 2024",
    src: "/companies/headstarter.jpg",
    backgroundColor: "#000000",
    fontColor: "#00e4b3",
    description: [
      "Building 5+ AI apps using NextJS, OpenAI, Pinecone, StripeAPI with 98% model accuracy, verified by 1000+ users",
      "Developed projects from design to deployment leading other engineering fellows using MVC design patterns",
      "Coached by Amazon, Bloomberg, and Capital One engineers on Agile, CI/CD, Git, and microservice patterns",
    ],
  },
  {
    position: "Full Stack Development Bootcamp",
    company: "Flatiron School",
    companyHref: "https://www.linkedin.com/school/the-flatiron-school/",
    date: "Jun 2023 - Sep 2023",
    src: "/logos/flatironlogo.png",
    backgroundColor: "#00b3e6",
    fontColor: "#000000",
    description: [
      "Full stack development bootcamp that covers the following core languages: JavaScript, React, Python, Flask.",
      "The program is split up into 5 different phases paired with exams and projects for each phase: an average of 40 hours of classwork required per week.",
      " Students learn front-end and back-end skills to develop projects collaboratively and individually.",
    ],
  },
  {
    position: "Emergency Medical Technician",
    company: "Ambulnz - DocGo",
    companyHref: "https://www.linkedin.com/company/docgo/",
    date: "May 2022 - Dec 2022",
    src: "/companies/docgo.jpeg",
    backgroundColor: "#01c0dd",
    fontColor: "#000000",
    description: [
      "Delivered pre-hospital care and emergency treatment to patients, while conducting on-scene patient assessments",
      "Communicated with patients and family to identify treatment based on medical history, maintaining compassion to calm patients",
      "Ensured compliance with DOT regulations and conducted safety inspections of ambulance and medical equipment ",
    ],
  },
  {
    position: "SUNY Stony Brook",
    company: "B.S in Biology",
    companyHref: "https://www.linkedin.com/in/samuel-ou-0510s/",
    date: "Aug 2019 - May 2023",
    src: "/logos/sbu.png",
    backgroundColor: "#9a0000",
    fontColor: "#ffffff",
    description: [
      "Completed 4 years of undergraduate degree in interdisciplinary biology",
      "Engaged in research projects focusing on biological sciences and computational methods",
      "Self studied DSA courses in my last year",
    ],
  },
];

export default Experiences;
